"""made WalletRequest

Revision ID: 856afc685805
Revises: 
Create Date: 2025-03-24 20:37:53.532605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856afc685805'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('trx_balance', sa.Integer(), nullable=True),
    sa.Column('bandwidth', sa.Integer(), nullable=True),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_requests_address'), 'wallet_requests', ['address'], unique=False)
    op.create_index(op.f('ix_wallet_requests_id'), 'wallet_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_requests_id'), table_name='wallet_requests')
    op.drop_index(op.f('ix_wallet_requests_address'), table_name='wallet_requests')
    op.drop_table('wallet_requests')
    # ### end Alembic commands ###
